# Module: zeek
# Docs: https://www.elastic.co/guide/en/beats/filebeat/7.x/filebeat-module-zeek.html
- module: zeek
  connection:
    enabled: true
    var.paths: ["/zeek/logs/conn.log"]
  dns:
      enabled: true
      var.paths: ["/zeek/logs/dns.log"]
  dpd:
      enabled: true
      var.paths: ["/zeek/logs/dpd.log"]
  files:
      enabled: true
      var.paths: ["/zeek/logs/files.log"]
  ftp:
      enabled: true
      var.paths: ["/zeek/logs/ftp.log"]
  http:
      enabled: true
      var.paths: ["/zeek/logs/http.log"]
  intel:
      enabled: true
      var.paths: ["/zeek/logs/intel.log"]
  irc:
      enabled: true
      var.paths: ["/zeek/logs/irc.log"]
  weird:
      enabled: true
      var.paths: ["/zeek/logs/weird.log"]